name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14.17.1-alpine3.12

    steps:
    
      - name: Code checkout
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: yarn install
        
      - name: Run test
        run: jest --runInBand --forceExit --coverage --json --outputFile=/home/runner/work/_actions/mattallty/jest-github-action/v1/dist/jest.results.json

      - name: Run test
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'echo done'
